import 'package:flutter/widgets.dart';

class AppStrings {
  AppStrings._();

  static const _en = {
    'dashboard': 'Dashboard',
    'overview': 'Overview',
    'new_scan': 'New Scan',
    'start_scanning': 'Start scanning',
    'scan_history': 'Scan History',
    'past_results': 'Past results',
    'settings': 'Settings',
    'configuration': 'Configuration',
    'total_scans': 'Total Scans',
    'vulnerabilities': 'Vulnerabilities',
    'security_score': 'Security Score',
    'active_threats': 'Active Threats',
    'vuln_distribution': 'Vulnerability Distribution by Severity',
    'scan_trends': 'Scan Trends (Last 30 Days)',
    'recent_scans': 'Recent Scans',
    'view_all': 'View All →',
    'target_url': 'Target URL',
    'date': 'Date',
    'status': 'Status',
    'risk_level': 'Risk Level',
    'completed': 'Completed',
    'failed': 'Failed',
    'critical': 'Critical',
    'high': 'High',
    'medium': 'Medium',
    'low': 'Low',
    'unknown': 'Unknown',
    'start_scan': 'Start Scan',
    'target_url_label': 'Target URL',
    'full_scan': 'Full Scan',
    'passive_only': 'Passive Only',
    'active_only': 'Active Only',
    'history_title': 'Scan History',
    'no_history': 'No history found',
    'results_title': 'Results',
    'risk_level_label': 'Risk Level',
    'findings': 'Findings',
    'light_mode': 'Light Mode',
    'dark_mode': 'Dark Mode',
    'aiConfiguration': 'AI Configuration',
    'deepseekApiKey': 'DeepSeek API Key',
    'aiModel': 'AI Model',
    'scanConfiguration': 'Scan Configuration',
    'requestTimeout': 'Request Timeout',
    'maxRetries': 'Max Retries',
    'enableWafEvasion': 'Enable WAF Evasion',
    'enableStealthMode': 'Enable Stealth Mode',
    'appearance': 'Appearance',
    'language': 'Language',
    'about': 'About',
    'appDescription': 'AI-Powered Cybersecurity & Vulnerability Scanning Tool',
    'backendStatus': 'Backend Status',
    'online': 'Online',
    'offline': 'Offline',
    'save': 'Save',
  };

  static const _tr = {
    'dashboard': 'Gösterge Paneli',
    'overview': 'Genel Bakış',
    'new_scan': 'Yeni Tarama',
    'start_scanning': 'Taramayı Başlat',
    'scan_history': 'Tarama Geçmişi',
    'past_results': 'Geçmiş Sonuçlar',
    'settings': 'Ayarlar',
    'configuration': 'Yapılandırma',
    'total_scans': 'Toplam Tarama',
    'vulnerabilities': 'Güvenlik Açıkları',
    'security_score': 'Güvenlik Puanı',
    'active_threats': 'Aktif Tehditler',
    'vuln_distribution': 'Önem Derecesine Göre Dağılım',
    'scan_trends': 'Tarama Trendleri (Son 30 Gün)',
    'recent_scans': 'Son Taramalar',
    'view_all': 'Tümünü Gör →',
    'target_url': 'Hedef URL',
    'date': 'Tarih',
    'status': 'Durum',
    'risk_level': 'Risk Seviyesi',
    'completed': 'Tamamlandı',
    'failed': 'Başarısız',
    'critical': 'Kritik',
    'high': 'Yüksek',
    'medium': 'Orta',
    'low': 'Düşük',
    'unknown': 'Bilinmiyor',
    'start_scan': 'Taramayı Başlat',
    'target_url_label': 'Hedef URL',
    'full_scan': 'Tam Tarama',
    'passive_only': 'Yalnızca Pasif',
    'active_only': 'Yalnızca Aktif',
    'history_title': 'Tarama Geçmişi',
    'no_history': 'Geçmiş bulunamadı',
    'results_title': 'Sonuçlar',
    'risk_level_label': 'Risk Seviyesi',
    'findings': 'Bulgular',
    'light_mode': 'Açık Mod',
    'dark_mode': 'Koyu Mod',
    'aiConfiguration': 'Yapay Zeka Ayarları',
    'deepseekApiKey': 'DeepSeek API Anahtarı',
    'aiModel': 'Yapay Zeka Modeli',
    'scanConfiguration': 'Tarama Ayarları',
    'requestTimeout': 'İstek Zaman Aşımı',
    'maxRetries': 'Maksimum Deneme',
    'enableWafEvasion': 'WAF Atlatmayı Etkinleştir',
    'enableStealthMode': 'Gizlilik Modunu Etkinleştir',
    'appearance': 'Görünüm',
    'language': 'Dil',
    'about': 'Hakkında',
    'appDescription':
        'Yapay Zeka Destekli Siber Güvenlik ve Zafiyet Tarama Aracı',
    'backendStatus': 'Sunucu Durumu',
    'online': 'Çevrimiçi',
    'offline': 'Çevrimdışı',
    'save': 'Kaydet',
  };

  static String get(BuildContext context, String key) {
    final locale = Localizations.localeOf(context).languageCode;
    if (locale == 'tr') {
      return _tr[key] ?? key;
    }
    return _en[key] ?? key;
  }
}
