"""
WAF (Web Application Firewall) Detection Module.
Detects WAF type from response headers, cookies, and body patterns.
"""

import logging
import re
from typing import Dict, List, Optional, Tuple

import httpx

logger = logging.getLogger("webscanpro.waf_detector")

# Known WAF signatures for detection
WAF_SIGNATURES: Dict[str, Dict] = {
    "Cloudflare": {
        "headers": {
            "server": ["cloudflare"],
            "cf-ray": [r".+"],
            "cf-cache-status": [r".+"],
        },
        "cookies": ["__cfduid"],
        "body_patterns": [
            r"cloudflare",
            r"attention required!",
            r"please enable cookies",
            r"under attack",
        ],
        "response_code": [403, 503],
    },
    "ModSecurity": {
        "headers": {
            "server": ["mod_security", "modsecurity", "NoScript"],
            "x-powered-by": ["Mod Security"],
        },
        "body_patterns": [
            r"mod_security",
            r"modsecurity",
            r"not acceptable",
            r"406 not acceptable",
        ],
        "response_code": [406, 500],
    },
    "AWS WAF": {
        "headers": {
            "x-amzn-requestid": [r".+"],
            "x-amz-cf-id": [r".+"],
            "x-amz-cf-pop": [r".+"],
        },
        "body_patterns": [
            r"request blocked",
            r"aws waf",
            r"wafddos",
        ],
        "response_code": [403],
    },
    "F5 BIG-IP ASM": {
        "headers": {
            "server": ["big-ip", "bigip"],
            "x-frame-options": ["deny"],
            "x-content-type-options": ["nosniff"],
        },
        "cookies": ["TS", "TS01", "TS03", "ASM"],
        "body_patterns": [
            r"the requested url was rejected",
            r"please consult with your administrator",
            r"support id",
        ],
        "response_code": [403, 500, 501],
    },
    "Akamai": {
        "headers": {
            "server": ["akamai"],
            "x-akamai-transformed": [r".+"],
            "x-akamai-request-id": [r".+"],
        },
        "body_patterns": [
            r"akamaighost",
            r"reference.*#",
            r"error reference number",
        ],
        "response_code": [403],
    },
    "Sucuri": {
        "headers": {
            "x-sucuri-id": [r".+"],
            "x-sucuri-cache": [r".+"],
            "x-sucuri-block": [r".+"],
        },
        "cookies": ["sucuri_cloudproxy"],
        "body_patterns": [
            r"sucuri",
            r"cloudproxy",
            r"website firewall",
        ],
        "response_code": [403],
    },
    "Barracuda": {
        "headers": {
            "server": ["barracuda"],
            "x-barracuda": [r".+"],
        },
        "body_patterns": [
            r"barracuda",
            r"blocked by barracuda",
        ],
        "response_code": [403, 500],
    },
    "Wordfence": {
        "headers": {
            "server": ["wordfence"],
        },
        "cookies": ["wfvt_", "wordfence_verifiedHuman"],
        "body_patterns": [
            r"wordfence",
            r"generated by wordfence",
            r"blocked by wordfence",
        ],
        "response_code": [403, 503],
    },
}


async def detect_waf(target_url: str) -> Tuple[Optional[str], float]:
    """
    Detect WAF type for the given target URL.

    Args:
        target_url: The URL to test.

    Returns:
        Tuple of (waf_name, confidence_score) where waf_name is None if no WAF detected.
    """
    logger.info(f"Detecting WAF for {target_url}")

    try:
        async with httpx.AsyncClient(
            verify=True,
            timeout=httpx.Timeout(10.0),
            follow_redirects=True,
        ) as client:
            # Send a potentially malicious request to trigger WAF
            malicious_payload = "?id=1' OR '1'='1' -- -"
            test_url = target_url.rstrip("/") + malicious_payload

            response = await client.get(
                test_url,
                headers={
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                    "AppleWebKit/537.36 (KHTML, like Gecko) "
                    "Chrome/120.0.0.0 Safari/537.36",
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
                },
            )

            return await _analyze_response(response, target_url)

    except httpx.TimeoutException:
        logger.warning(f"Timeout detecting WAF for {target_url}")
        return None, 0.0
    except Exception as e:
        logger.error(f"Error detecting WAF for {target_url}: {e}")
        return None, 0.0


async def _analyze_response(
    response: httpx.Response, target_url: str
) -> Tuple[Optional[str], float]:
    """Analyze response headers, cookies, and body for WAF signatures."""
    headers = dict(response.headers)
    body_text = response.text.lower()
    status_code = response.status_code
    cookies = dict(response.cookies.items())

    best_match: Optional[str] = None
    best_score: float = 0.0

    for waf_name, signatures in WAF_SIGNATURES.items():
        score = 0.0
        checks = 0

        # Check headers
        if "headers" in signatures:
            for header, patterns in signatures["headers"].items():
                header_value = headers.get(header, "").lower()
                header_value_lower = headers.get(header.lower(), "").lower()
                actual_value = header_value or header_value_lower

                if actual_value:
                    for pattern in patterns:
                        if re.search(pattern, actual_value, re.IGNORECASE):
                            score += 0.4
                            break
                checks += 1

        # Check cookies
        if "cookies" in signatures:
            for cookie_pattern in signatures["cookies"]:
                for cookie_name in cookies:
                    if re.search(cookie_pattern, cookie_name, re.IGNORECASE):
                        score += 0.3
                checks += 1

        # Check body patterns
        if "body_patterns" in signatures:
            for pattern in signatures["body_patterns"]:
                if re.search(pattern, body_text, re.IGNORECASE):
                    score += 0.3
                checks += 1

        # Check response codes
        if "response_code" in signatures:
            if status_code in signatures["response_code"]:
                score += 0.2
            checks += 1

        # Normalize score
        if checks > 0:
            score = min(score / checks, 1.0)

        if score > best_score:
            best_score = score
            best_match = waf_name

    confidence_threshold = 0.25
    if best_score < confidence_threshold:
        return None, 0.0

    logger.info(f"WAF detected: {best_match} (confidence: {best_score:.2f})")
    return best_match, round(best_score, 2)
