"""add_error_message_to_scan_sessions

Revision ID: 7dcdf8c9f5c8
Revises: 5b373a395199
Create Date: 2026-05-02 20:01:56.924937

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7dcdf8c9f5c8"
down_revision: Union[str, None] = "5b373a395199"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scan_sessions", sa.Column("error_message", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scan_sessions", "error_message")
    # ### end Alembic commands ###
